const express = require('express');
const path = require('path');
const app = express();
const PORT = 3030;

// Serve static files from the dist directory generated by the build
app.use(express.static(path.join(__dirname, 'dist')));

// Handle SPA routing: return index.html for any unknown route
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// Listen on all network interfaces
app.listen(PORT, '0.0.0.0', () => {
  console.log(`NC Business Atlas server running on port ${PORT}`);
});
